apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: autoscale-cart
spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: cart
    minReplicas: 2
    maxReplicas: 6
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
