apiVersion: v1
kind: Service
metadata:
 labels:
   app: cart-service
 name: cart-service
spec:
 ports:
 - port: 8080
   protocol: TCP
   targetPort: 8080
 selector:
   app: cart
   color: {{DEPLOYMENT_COLOR}}
 type: ClusterIP