apiVersion: v1
kind: Service
metadata:
 labels:
   app: product-service
 name: product-service
spec:
 ports:
 - port: 8080
   protocol: TCP
   targetPort: 8080
 selector:
   app: product
   color: {{DEPLOYMENT_COLOR}}
 type: ClusterIP